### ISSUE TITLE
facing slow performance in process Info

### ISSUE THREAD

**Issue by profahad** [blacksmoke26/pr-sandbox#4]
i am using current method but getting incorrect result with slow speed.

**Comment by blacksmoke26** [comment]
Iure amet ut nisi odit quia est eligendi. Incidunt repudiandae quaerat voluptatum sit sint delectus illo. Corrupti sit qui facilis sed rerum ut dolores. Excepturi qui et iure nobis dolorem _consequatur quia_ animi. Rerum rem eos.

**Comment by fahadjamal** [comment]
we have to work on the above code to fix this issue.

**Comment by usama036** [comment]
we are facing slow perfomance issue

**Comment by blacksmoke26** [comment]
@profahad Did you see a performance gain from a certain point?

**Comment by blacksmoke26** [comment]
What about the above statement?

@fahadjamal @usama036

**Comment by blacksmoke26** [comment]
Done. Thank you!
